minimumReleaseAge: 1440
blockExoticSubdeps: true
allowBuilds:
  core-js: true
  core-js-pure: true
overrides:
  '@tootallnate/once@<2.0.1': ^2.0.1
  nth-check@<2.0.1: ^2.0.1
  postcss@<8.4.31: ^8.4.31
  postcss@<8.5.10: ^8.5.10
  serialize-javascript@<=7.0.2: ^7.0.3
  serialize-javascript@>=5.0.0 <7.0.5: ^7.0.5
  underscore@<=1.13.7: ^1.13.8
  uuid@<11.1.1: ^11.1.1
  webpack-dev-server@<5.2.5: ^5.2.5
  webpack-dev-server@<=5.2.0: ^5.2.1
  webpack-dev-server@<=5.2.3: ^5.2.4
minimumReleaseAgeExclude:
  - nth-check@2.0.1
  - webpack-dev-server@5.2.1
  - postcss@8.4.31
  - serialize-javascript@7.0.3
  - postcss@8.5.10
  - underscore@1.13.8
  - webpack-dev-server@5.2.4
  - '@tootallnate/once@2.0.1'
  - serialize-javascript@7.0.5
  - uuid@11.1.1
  - webpack-dev-server@5.2.5
